[["alloc::vec::Vec::new"]]
marker = "safe_source"
on_return = true

[["core::iter::traits::collect::IntoIterator::into_iter"]]
marker = "into_iter"
on_return = true

[["core::iter::traits::iterator::Iterator::next"]]
marker = "next"
on_return = true

[["std::io::_print"]]
marker = "sink"
on_argument = [0]

